import './globals.css'
import type { Metadata } from 'next'
import { Locale, i18n } from '@/i18n.config'
import Header from './components/header'
import { getDictionary } from '@/lib/dictionary'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Language Toggle App Template',
  description: 'Generated by www.gongool.dev'
}


// Add this type to handle direction
type Direction = 'ltr' | 'rtl'

// Add this helper function
const getDirection = (locale: Locale): Direction => {
  return locale === 'ar' ? 'rtl' : 'ltr'
}


export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}



export default function RootLayout({
  children,
  params: { lang }
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={lang} dir={getDirection(lang)}>
      <body className={`${getDirection(lang) === 'rtl' ? 'font-arabic' : 'font-english'}`}>
        <Header lang={lang} />
        {children}
      </body>
    </html>
  )
}


